trigger:
  - main  # Trigger pipeline on commits to the main branch

pool:
  name: 'Default'  # Use the name of your self-hosted agent pool

steps:
# 1. Checkout the GitHub repository (fetches your jar file)
- checkout: self
  displayName: 'Checkout Repository'

# 2. Verify Java installation 
- script: |
    java -version
  displayName: 'Verify Java Installation'

# 3. Run the Talend Job using the .jar file
- script: |
     $(Build.SourcesDirectory)\MyRESTService_0.1\MyRESTService\MyRESTService_run.bat
  displayName: 'Run BAT file'